/*
 * Generated by scripts/generate-cards.mjs — do not edit by hand.
 * Run `npm run cards:generate` after changing web/public/coc/cards/manifest.json.
 *
 * The sixty cards of the collecting event: id, category, name, and the path to
 * the one vendored picture of each. A held card shows it in colour; a card the
 * base lacks shows the same image under a CSS greyscale filter, so there is a
 * single file per card rather than a colour/greyscale pair.
 *
 * This module is **tracked**, unlike the art it points at. web/public/coc/ is
 * gitignored, so a fresh clone — and any host that has not been given the images
 * — has this list but none of the pictures. That is the supported state: the
 * grid still renders sixty named cards, and `GameIcon` removes an image that
 * fails to load rather than showing a broken-image glyph or collapsing the cell.
 *
 * The card art is derived from the wiki art vendored by
 * `scripts/fetch-wiki-art.mjs`, whose per-file provenance lives in
 * `wiki-art.generated.ts`; the manifest's `art_source` records which one each
 * card came from. It is Supercell's, used under their Fan Content Policy.
 *
 * The manifest's `collected` and `confidence` fields are **not** carried
 * across. They are notes about how each image was sourced, not inventory;
 * inventory is per base, entered by hand, and lives in `card_inventory`.
 */
import type { CardCategory } from '@coc/shared'

export interface GeneratedCard {
  /** 1…60, contiguous. Also the primary key component in `card_inventory`. */
  readonly id: number
  readonly category: CardCategory
  readonly name: string
  /**
   * The card's art. Shown in colour when the base holds at least one, and under a
   * CSS greyscale filter when it holds none. May not exist on disk.
   */
  readonly image: string
}

export const CARDS: readonly GeneratedCard[] = [
  { id: 1, category: "Elixir", name: "Barbarian", image: "/coc/wiki/troops/barbarian.webp" },
  { id: 2, category: "Elixir", name: "Archer", image: "/coc/wiki/troops/archer.webp" },
  { id: 3, category: "Elixir", name: "Giant", image: "/coc/wiki/troops/giant.webp" },
  { id: 4, category: "Elixir", name: "Goblin", image: "/coc/wiki/troops/goblin.webp" },
  { id: 5, category: "Elixir", name: "Wall Breaker", image: "/coc/wiki/troops/wall-breaker.webp" },
  { id: 6, category: "Elixir", name: "Balloon", image: "/coc/wiki/troops/balloon.webp" },
  { id: 7, category: "Elixir", name: "Wizard", image: "/coc/wiki/troops/wizard.webp" },
  { id: 8, category: "Elixir", name: "Healer", image: "/coc/wiki/troops/healer.webp" },
  { id: 9, category: "Elixir", name: "Dragon", image: "/coc/wiki/troops/dragon.webp" },
  { id: 10, category: "Elixir", name: "P.E.K.K.A", image: "/coc/wiki/troops/p-e-k-k-a.webp" },
  { id: 11, category: "Elixir", name: "Baby Dragon", image: "/coc/wiki/troops/baby-dragon.webp" },
  { id: 12, category: "Elixir", name: "Miner", image: "/coc/wiki/troops/miner.webp" },
  { id: 13, category: "Elixir", name: "Electro Dragon", image: "/coc/wiki/troops/electro-dragon.webp" },
  { id: 14, category: "Elixir", name: "Yeti", image: "/coc/wiki/troops/yeti.webp" },
  { id: 15, category: "Elixir", name: "Dragon Rider", image: "/coc/wiki/troops/dragon-rider.webp" },
  { id: 16, category: "Elixir", name: "Electro Titan", image: "/coc/wiki/troops/electro-titan.webp" },
  { id: 17, category: "Elixir", name: "Root Rider", image: "/coc/wiki/troops/root-rider.webp" },
  { id: 18, category: "Elixir", name: "Thrower", image: "/coc/wiki/troops/thrower.webp" },
  { id: 19, category: "Elixir", name: "Meteor Golem", image: "/coc/wiki/troops/meteor-golem.webp" },
  { id: 20, category: "Dark Elixir", name: "Minion", image: "/coc/wiki/troops/minion.webp" },
  { id: 21, category: "Dark Elixir", name: "Hog Rider", image: "/coc/wiki/troops/hog-rider.webp" },
  { id: 22, category: "Dark Elixir", name: "Valkyrie", image: "/coc/wiki/troops/valkyrie.webp" },
  { id: 23, category: "Dark Elixir", name: "Golem", image: "/coc/wiki/troops/golem.webp" },
  { id: 24, category: "Dark Elixir", name: "Witch", image: "/coc/wiki/troops/witch.webp" },
  { id: 25, category: "Dark Elixir", name: "Lava Hound", image: "/coc/wiki/troops/lava-hound.webp" },
  { id: 26, category: "Dark Elixir", name: "Bowler", image: "/coc/wiki/troops/bowler.webp" },
  { id: 27, category: "Dark Elixir", name: "Ice Golem", image: "/coc/wiki/troops/ice-golem.webp" },
  { id: 28, category: "Dark Elixir", name: "Headhunter", image: "/coc/wiki/troops/headhunter.webp" },
  { id: 29, category: "Dark Elixir", name: "Apprentice Warden", image: "/coc/wiki/troops/apprentice-warden.webp" },
  { id: 30, category: "Dark Elixir", name: "Druid", image: "/coc/wiki/troops/druid.webp" },
  { id: 31, category: "Dark Elixir", name: "Furnace", image: "/coc/wiki/troops/furnace.webp" },
  { id: 32, category: "Dark Elixir", name: "Ruin Witch", image: "/coc/wiki/troops/ruin-witch.webp" },
  { id: 33, category: "Builder Base", name: "Raged Barbarian", image: "/coc/wiki/troops/raged-barbarian.webp" },
  { id: 34, category: "Builder Base", name: "Sneaky Archer", image: "/coc/wiki/troops/sneaky-archer.webp" },
  { id: 35, category: "Builder Base", name: "Boxer Giant", image: "/coc/wiki/troops/boxer-giant.webp" },
  { id: 36, category: "Builder Base", name: "Beta Minion", image: "/coc/wiki/troops/beta-minion.webp" },
  { id: 37, category: "Builder Base", name: "Bomber", image: "/coc/wiki/troops/bomber.webp" },
  { id: 38, category: "Builder Base", name: "Baby Dragon (Builder)", image: "/coc/wiki/troops/baby-dragon.webp" },
  { id: 39, category: "Builder Base", name: "Cannon Cart", image: "/coc/wiki/troops/cannon-cart.webp" },
  { id: 40, category: "Builder Base", name: "Night Witch", image: "/coc/wiki/troops/night-witch.webp" },
  { id: 41, category: "Builder Base", name: "Drop Ship", image: "/coc/wiki/troops/drop-ship.webp" },
  { id: 42, category: "Builder Base", name: "Power P.E.K.K.A", image: "/coc/wiki/troops/power-p-e-k-k-a.webp" },
  { id: 43, category: "Builder Base", name: "Hog Glider", image: "/coc/wiki/troops/hog-glider.webp" },
  { id: 44, category: "Super Troop", name: "Super Barbarian", image: "/coc/wiki/troops/super-barbarian.webp" },
  { id: 45, category: "Super Troop", name: "Super Archer", image: "/coc/wiki/troops/super-archer.webp" },
  { id: 46, category: "Super Troop", name: "Super Giant", image: "/coc/wiki/troops/super-giant.webp" },
  { id: 47, category: "Super Troop", name: "Sneaky Goblin", image: "/coc/wiki/troops/sneaky-goblin.webp" },
  { id: 48, category: "Super Troop", name: "Super Wall Breaker", image: "/coc/wiki/troops/super-wall-breaker.webp" },
  { id: 49, category: "Super Troop", name: "Rocket Balloon", image: "/coc/wiki/troops/rocket-balloon.webp" },
  { id: 50, category: "Super Troop", name: "Super Wizard", image: "/coc/wiki/troops/super-wizard.webp" },
  { id: 51, category: "Super Troop", name: "Super Dragon", image: "/coc/wiki/troops/super-dragon.webp" },
  { id: 52, category: "Super Troop", name: "Inferno Dragon", image: "/coc/wiki/troops/inferno-dragon.webp" },
  { id: 53, category: "Super Troop", name: "Super Miner", image: "/coc/wiki/troops/super-miner.webp" },
  { id: 54, category: "Super Troop", name: "Super Yeti", image: "/coc/wiki/troops/super-yeti.webp" },
  { id: 55, category: "Super Troop", name: "Super Minion", image: "/coc/wiki/troops/super-minion.webp" },
  { id: 56, category: "Super Troop", name: "Super Hog Rider", image: "/coc/wiki/troops/super-hog-rider.webp" },
  { id: 57, category: "Super Troop", name: "Super Valkyrie", image: "/coc/wiki/troops/super-valkyrie.webp" },
  { id: 58, category: "Super Troop", name: "Super Witch", image: "/coc/wiki/troops/super-witch.webp" },
  { id: 59, category: "Super Troop", name: "Ice Hound", image: "/coc/wiki/troops/ice-hound.webp" },
  { id: 60, category: "Super Troop", name: "Super Bowler", image: "/coc/wiki/troops/super-bowler.webp" },
]
