/*
 * Generated by scripts/generate-cards.mjs — do not edit by hand.
 * Run `npm run cards:generate` after changing web/public/coc/cards/manifest.json.
 *
 * The sixty cards of the collecting event: id, category, name, and the path to
 * the one vendored picture of each. A held card shows it in color; a card the
 * base lacks shows the same image under a CSS grayscale filter, so there is a
 * single file per card rather than a color/grayscale pair.
 *
 * This module is **tracked**, unlike the art it points at. web/public/coc/ is
 * gitignored, so a fresh clone — and any host that has not been given the images
 * — has this list but none of the pictures. That is the supported state: the
 * grid still renders sixty named cards, and `GameIcon` removes an image that
 * fails to load rather than showing a broken-image glyph or collapsing the cell.
 *
 * The card art is a purpose-made 256x320 portrait set, each file already framed
 * on its own subject — **not** derived from the wiki thumbnails
 * `fetch-wiki-art.mjs` vendors, which is why the tiles are framed whole rather
 * than cropped. No script regenerates it: it exists only where it was assembled,
 * so a host is given the files by hand. Per-card provenance is
 * `scripts/card-art-sources.csv`, and the manifest's `art_source` records it.
 * It is Supercell's, used under their Fan Content Policy.
 *
 * The manifest's `collected` and `confidence` fields are **not** carried
 * across. They are notes about how each image was sourced, not inventory;
 * inventory is per base, entered by hand, and lives in `card_inventory`.
 */
import type { CardCategory } from '@coc/shared'

export interface GeneratedCard {
  /** 1…60, contiguous. Also the primary key component in `card_inventory`. */
  readonly id: number
  readonly category: CardCategory
  readonly name: string
  /**
   * The card's art. Shown in color when the base holds at least one, and under a
   * CSS grayscale filter when it holds none. May not exist on disk.
   */
  readonly image: string
}

export const CARDS: readonly GeneratedCard[] = [
  { id: 1, category: "Elixir", name: "Barbarian", image: "/coc/cards/elixir_01_barbarian.png" },
  { id: 2, category: "Elixir", name: "Archer", image: "/coc/cards/elixir_02_archer.png" },
  { id: 3, category: "Elixir", name: "Giant", image: "/coc/cards/elixir_03_giant.png" },
  { id: 4, category: "Elixir", name: "Goblin", image: "/coc/cards/elixir_04_goblin.png" },
  { id: 5, category: "Elixir", name: "Wall Breaker", image: "/coc/cards/elixir_05_wall_breaker.png" },
  { id: 6, category: "Elixir", name: "Balloon", image: "/coc/cards/elixir_06_balloon.png" },
  { id: 7, category: "Elixir", name: "Wizard", image: "/coc/cards/elixir_07_wizard.png" },
  { id: 8, category: "Elixir", name: "Healer", image: "/coc/cards/elixir_08_healer.png" },
  { id: 9, category: "Elixir", name: "Dragon", image: "/coc/cards/elixir_09_dragon.png" },
  { id: 10, category: "Elixir", name: "P.E.K.K.A", image: "/coc/cards/elixir_10_pekka.png" },
  { id: 11, category: "Elixir", name: "Baby Dragon", image: "/coc/cards/elixir_11_baby_dragon.png" },
  { id: 12, category: "Elixir", name: "Miner", image: "/coc/cards/elixir_12_miner.png" },
  { id: 13, category: "Elixir", name: "Electro Dragon", image: "/coc/cards/elixir_13_electro_dragon.png" },
  { id: 14, category: "Elixir", name: "Yeti", image: "/coc/cards/elixir_14_yeti.png" },
  { id: 15, category: "Elixir", name: "Dragon Rider", image: "/coc/cards/elixir_15_dragon_rider.png" },
  { id: 16, category: "Elixir", name: "Electro Titan", image: "/coc/cards/elixir_16_electro_titan.png" },
  { id: 17, category: "Elixir", name: "Root Rider", image: "/coc/cards/elixir_17_root_rider.png" },
  { id: 18, category: "Elixir", name: "Thrower", image: "/coc/cards/elixir_18_thrower.png" },
  { id: 19, category: "Elixir", name: "Meteor Golem", image: "/coc/cards/elixir_19_meteor_golem.png" },
  { id: 20, category: "Dark Elixir", name: "Minion", image: "/coc/cards/dark_elixir_20_minion.png" },
  { id: 21, category: "Dark Elixir", name: "Hog Rider", image: "/coc/cards/dark_elixir_21_hog_rider.png" },
  { id: 22, category: "Dark Elixir", name: "Valkyrie", image: "/coc/cards/dark_elixir_22_valkyrie.png" },
  { id: 23, category: "Dark Elixir", name: "Golem", image: "/coc/cards/dark_elixir_23_golem.png" },
  { id: 24, category: "Dark Elixir", name: "Witch", image: "/coc/cards/dark_elixir_24_witch.png" },
  { id: 25, category: "Dark Elixir", name: "Lava Hound", image: "/coc/cards/dark_elixir_25_lava_hound.png" },
  { id: 26, category: "Dark Elixir", name: "Bowler", image: "/coc/cards/dark_elixir_26_bowler.png" },
  { id: 27, category: "Dark Elixir", name: "Ice Golem", image: "/coc/cards/dark_elixir_27_ice_golem.png" },
  { id: 28, category: "Dark Elixir", name: "Headhunter", image: "/coc/cards/dark_elixir_28_headhunter.png" },
  { id: 29, category: "Dark Elixir", name: "Apprentice Warden", image: "/coc/cards/dark_elixir_29_apprentice_warden.png" },
  { id: 30, category: "Dark Elixir", name: "Druid", image: "/coc/cards/dark_elixir_30_druid.png" },
  { id: 31, category: "Dark Elixir", name: "Furnace", image: "/coc/cards/dark_elixir_31_furnace.png" },
  { id: 32, category: "Dark Elixir", name: "Ruin Witch", image: "/coc/cards/dark_elixir_32_ruin_witch.png" },
  { id: 33, category: "Builder Base", name: "Raged Barbarian", image: "/coc/cards/builder_base_33_raged_barbarian.png" },
  { id: 34, category: "Builder Base", name: "Sneaky Archer", image: "/coc/cards/builder_base_34_sneaky_archer.png" },
  { id: 35, category: "Builder Base", name: "Boxer Giant", image: "/coc/cards/builder_base_35_boxer_giant.png" },
  { id: 36, category: "Builder Base", name: "Beta Minion", image: "/coc/cards/builder_base_36_beta_minion.png" },
  { id: 37, category: "Builder Base", name: "Bomber", image: "/coc/cards/builder_base_37_bomber.png" },
  { id: 38, category: "Builder Base", name: "Baby Dragon (Builder)", image: "/coc/cards/builder_base_38_baby_dragon_builder.png" },
  { id: 39, category: "Builder Base", name: "Cannon Cart", image: "/coc/cards/builder_base_39_cannon_cart.png" },
  { id: 40, category: "Builder Base", name: "Night Witch", image: "/coc/cards/builder_base_40_night_witch.png" },
  { id: 41, category: "Builder Base", name: "Drop Ship", image: "/coc/cards/builder_base_41_drop_ship.png" },
  { id: 42, category: "Builder Base", name: "Power P.E.K.K.A", image: "/coc/cards/builder_base_42_power_pekka.png" },
  { id: 43, category: "Builder Base", name: "Hog Glider", image: "/coc/cards/builder_base_43_hog_glider.png" },
  { id: 44, category: "Super Troop", name: "Super Barbarian", image: "/coc/cards/super_troop_44_super_barbarian.png" },
  { id: 45, category: "Super Troop", name: "Super Archer", image: "/coc/cards/super_troop_45_super_archer.png" },
  { id: 46, category: "Super Troop", name: "Super Giant", image: "/coc/cards/super_troop_46_super_giant.png" },
  { id: 47, category: "Super Troop", name: "Sneaky Goblin", image: "/coc/cards/super_troop_47_sneaky_goblin.png" },
  { id: 48, category: "Super Troop", name: "Super Wall Breaker", image: "/coc/cards/super_troop_48_super_wall_breaker.png" },
  { id: 49, category: "Super Troop", name: "Rocket Balloon", image: "/coc/cards/super_troop_49_rocket_balloon.png" },
  { id: 50, category: "Super Troop", name: "Super Wizard", image: "/coc/cards/super_troop_50_super_wizard.png" },
  { id: 51, category: "Super Troop", name: "Super Dragon", image: "/coc/cards/super_troop_51_super_dragon.png" },
  { id: 52, category: "Super Troop", name: "Inferno Dragon", image: "/coc/cards/super_troop_52_inferno_dragon.png" },
  { id: 53, category: "Super Troop", name: "Super Miner", image: "/coc/cards/super_troop_53_super_miner.png" },
  { id: 54, category: "Super Troop", name: "Super Yeti", image: "/coc/cards/super_troop_54_super_yeti.png" },
  { id: 55, category: "Super Troop", name: "Super Minion", image: "/coc/cards/super_troop_55_super_minion.png" },
  { id: 56, category: "Super Troop", name: "Super Hog Rider", image: "/coc/cards/super_troop_56_super_hog_rider.png" },
  { id: 57, category: "Super Troop", name: "Super Valkyrie", image: "/coc/cards/super_troop_57_super_valkyrie.png" },
  { id: 58, category: "Super Troop", name: "Super Witch", image: "/coc/cards/super_troop_58_super_witch.png" },
  { id: 59, category: "Super Troop", name: "Ice Hound", image: "/coc/cards/super_troop_59_ice_hound.png" },
  { id: 60, category: "Super Troop", name: "Super Bowler", image: "/coc/cards/super_troop_60_super_bowler.png" },
]
