/*
 * Generated by scripts/fetch-coc-assets.mjs — do not edit by hand.
 *
 * Which league and label icons are vendored under web/public/coc. Anything not
 * in these sets (a league or label added after the last run) falls back to the
 * CDN URL the API supplied, so a stale set degrades to the old behaviour rather
 * than a broken image.
 */

const LEAGUE_IDS = new Set([
  29000000,
  29000001,
  29000002,
  29000003,
  29000004,
  29000005,
  29000006,
  29000007,
  29000008,
  29000009,
  29000010,
  29000011,
  29000012,
  29000013,
  29000014,
  29000015,
  29000016,
  29000017,
  29000018,
  29000019,
  29000020,
  29000021,
  29000022,
])

const LABEL_IDS = new Set([
  56000000,
  56000001,
  56000002,
  56000003,
  56000004,
  56000005,
  56000006,
  56000007,
  56000008,
  56000009,
  56000010,
  56000011,
  56000012,
  56000013,
  56000014,
  56000015,
  56000016,
  57000000,
  57000001,
  57000002,
  57000003,
  57000004,
  57000005,
  57000006,
  57000007,
  57000008,
  57000009,
  57000010,
  57000011,
  57000012,
  57000013,
  57000014,
  57000015,
  57000016,
  57000017,
  57000018,
])

/** Local league badge when we have it, else the API's CDN URL. */
export function leagueIcon(id: number, remote: string): string {
  return LEAGUE_IDS.has(id) ? `/coc/leagues/${id}.png` : remote
}

/** Local label icon when we have it, else the API's CDN URL. */
export function labelIcon(id: number, remote: string): string {
  return LABEL_IDS.has(id) ? `/coc/labels/${id}.png` : remote
}
